
! Define the needed argument commands
#define BUD_BLAS(A,B,D) BUD_CC5(A,_,B,_,D)
#define BUD_BLASX(A,B) BUD_CC2(A,B)


! project-buds -- local file settings
!     Anything below this line may be overwritten by scripts
!     Below are non-editable settings

! Local Variables:
!  mode: f90
!  f90-if-indent: 2
!  f90-type-indent: 2
!  f90-associate-indent: 2
!  f90-continuation-indent: 2
!  f90-structure-indent: 2
!  f90-critical-indent: 2
!  f90-program-indent: 2
!  f90-do-indent: 2
! End: